### ISSUE TITLE
Lemma of ἐρρέθη

### ISSUE THREAD

**Issue by aminusfu** [morphgnt/sblgnt#16]
For example, Matt 5:21 reads: `010521 V- 3API-S-- ἐρρέθη ἐρρέθη ἐρρέθη ῥέω` The word "ῥέω" means ["flow"](http://www.perseus.tufts.edu/hopper/morph?l=%E1%BF%A5%CE%AD%CF%89&la=greek#lexicon), whereas this is most likely a form of "ἐρῶ", ["speak"](http://www.perseus.tufts.edu/hopper/morph?l=%E1%BC%90%CF%81%CF%81%CE%AD%CE%B8%CE%B7&la=greek#lexicon).

All occurrences of this form share the same incorrect lemma.

**Comment by jtauber** [comment]
*Friberg, Friberg & Miller* do give the lemma as εἶπον but in that entry point out the aorist passive comes from εἵρω. I can clarify this in the morphological lexicon but still need to think about the most consistent thing to use in the MorphGNT itself. Might even make sense to use λέγω.

**Comment by jtauber** [comment]
Give εἶπον itself gives its lemma as λέγω (and that's basically how suppletion is generally handled) I think λέγω makes the most sense and will make that change shortly.
