### ISSUE TITLE
Vocative plurals of ὁδηγός are marked singular

### ISSUE THREAD

**Issue by aminusfu** [morphgnt/sblgnt#17]
Both occurrences are marked as singular but are clearly plural as all the other adjectives etc in the same ~~mood~~ phrase are plural:

Mt 23:16	woe to you, blind guides the ones who say...
Οὐαὶ ὑμῖν, ὁδηγοὶ τυφλοὶ οἱ λέγοντες·
Mt 23:24	blind guides, the ones who filter...
ὁδηγοὶ τυφλοί, οἱ διϋλίζοντες...

**Comment by jtauber** [comment]
This was actually fixed Oct 14, 2013.
