### ISSUE TITLE
ἀπολελυμένην has wrong lemma

### ISSUE THREAD

**Issue by aminusfu** [morphgnt/sblgnt#23]
ἀπολελυμένην (and only that form: participle, passive, accusative, perfect, feminine, singular) incorrectly has ἀπολείπω as its lemma, when it should be ἀπολύω. This occurs in two places, Lk 16:18 and Mt 5:32, but not the third, Mt 19:9 for some reason.

**Comment by jtauber** [comment]
Fixed.
