### ISSUE TITLE
inconsistency in mapping forms of δεῖ & δέω

### ISSUE THREAD

**Issue by e-ehrhardt** [morphgnt/sblgnt#24]
I'm not quite clear on the relationship between these verbs, whether the intention was to list δεῖ as just a form under δέω, or to have separate lemmas for δέω and δεῖ (with δεῖ  containing the impersonal usages).

But either way, what morphGNT ends up with is this:

Forms of the lemma <δεῖ> are limited to:
- ἔδει  {'3IAI-S--': 16}

Forms of the lemma <δέω> include: 
- δεῖ  {'3PAI-S--': 77}
- and everything else.

**Comment by jtauber** [comment]
A decision would have to be made how to handle impersonal verbs in general and then potentially disambiguate the 3rd singular forms (if we decide to treat impersonal verbs differently from their base verb)

**Comment by e-ehrhardt** [comment]
I'm ok with a decision to not specially treat impersonal verbs.  But in that case, ἔδει should have δέω as its lemma, not δεῖ, right?  It just seems weird for form ἔδει to map to the lemma δεῖ, but the form δεῖ to map to the lemma δέω.

**Comment by jtauber** [comment]
Right, either way a change has to be made. But which change to make depends on a larger decision of how to model impersonal verbs. And if we keep δεῖ as a lemma we still need to decide which cases where the form is δεῖ are impersonal or not.

**Comment by jtauber** [comment]
@emg do you have any thoughts here?

**Comment by jtauber** [comment]
I think for now I'll change things to use δέω in all cases. It tips the balance towards a more formal analysis and we can always work out a way of indicating impersonal uses later (which is not a morphological question)
