### ISSUE TITLE
Acts 7:31

### ISSUE THREAD

**Issue by javimat** [morphgnt/sblgnt#29]
In Acts 7:31, ἐθαύμασεν parsed as **Imperfect**; shouldn't it be **Aorist**?
```
Line 4123:
050731 V- 3IAI-S-- ⸀ἐθαύμασεν ἐθαύμασεν ἐθαύμασε(ν) θαυμάζω
```

**Comment by jtauber** [comment]
This raises a question about how far the *morphological* tagging should go to retain ambiguities at the morphological level. Once I split tense and aspect I *can* introduce the notion of “past but unknown aspect” but the question is whether I *should*.

**Comment by javimat** [comment]
Maybe I'm missing something here. I don't think there is an ambiguity:
ἐθαύμα**ζ**εν -> Imperfect
ἐθαύμα**σ**εν -> Aorist

**Comment by javimat** [comment]
Maybe I'm missing something here. I don't think there is ambiguity:
ἐθαύμα**σ**εν -> Aorist
ἐθαύμα**ζ**εν -> Imperfect

**Comment by jtauber** [comment]
Yes, sorry, you're correct and I'll get it fixed in the database. I was more musing on the general question of ambiguity in the morphology (as this is a case where knowledge of the stem is needed) but overapplied it in this case.
