### ISSUE TITLE
μακράν or μακρός lemma for ASF μακράν?

### ISSUE THREAD

**Issue by jtauber** [morphgnt/sblgnt#33]
From https://github.com/morphgnt/sblgnt/issues/32

    A- ----ASF- μακράν => μακράν or μακρός

These are the places with lemma μακράν

    62-Mk-morphgnt.txt:021234 A- ----ASF- μακρὰν μακρὰν μακράν μακράν
    63-Lk-morphgnt.txt:030706 A- ----ASF- μακρὰν μακρὰν μακράν μακράν
    63-Lk-morphgnt.txt:031520 A- ----ASF- μακρὰν μακρὰν μακράν μακράν

These are the places with the same form/tag with lemma μακρός

    61-Mt-morphgnt.txt:010830 A- ----ASF- μακρὰν μακρὰν μακράν μακρός
    63-Lk-morphgnt.txt:031513 A- ----ASF- μακράν, μακράν μακράν μακρός
    63-Lk-morphgnt.txt:031912 A- ----ASF- μακρὰν μακρὰν μακράν μακρός
    64-Jn-morphgnt.txt:042108 A- ----ASF- μακρὰν μακρὰν μακράν μακρός
    65-Ac-morphgnt.txt:050239 A- ----ASF- μακρὰν μακρὰν μακράν μακρός
    65-Ac-morphgnt.txt:051727 A- ----ASF- μακρὰν μακρὰν μακράν μακρός
    65-Ac-morphgnt.txt:052221 A- ----ASF- μακρὰν μακρὰν μακράν μακρός
    70-Eph-morphgnt.txt:100213 A- ----ASF- μακρὰν μακρὰν μακράν μακρός
    70-Eph-morphgnt.txt:100217 A- ----ASF- μακρὰν μακρὰν μακράν μακρός

**Comment by emg** [comment]
I'd say MAKRA/N is an adverb. Syntactically, it appears to be used as such in the first three instances listed.

**Comment by jtauber** [comment]
@emg So we'll keep the second group of 9 as-is but change the first three to `D- --------` (keeping the lemmatization)?

**Comment by emg** [comment]
Yes, that is what I meant.
