### ISSUE TITLE
fix σύνιημι lemmatization

### ISSUE THREAD

**Issue by jtauber** [morphgnt/sblgnt#37]
σύνιημι isn't even valid accentuation. Should this just be corrected to συνίημι or is something else going on?

**Comment by jtauber** [comment]
Part of #32 as well.

**Comment by emg** [comment]
What's the reference?

**Comment by jtauber** [comment]
65-Ac-morphgnt.txt:052826 V- 2AAS-P-- συνῆτε, συνῆτε συνῆτε σύνιημι
p

**Comment by emg** [comment]
Thanks.

Looking at the context (it is a quote from the OT), it looks like the meaning matches SUNI/HMI.  Looking at Robinson's Westcott-Hort, he says it is Strong's number 4920, which again is SUNI/HMI.  So I don't think anything special is going on, other than a typo :-).
