### ISSUE TITLE
lemmatization of προώρισε(ν)

### ISSUE THREAD

**Issue by jtauber** [morphgnt/sblgnt#40]
from #32 

    65-Ac-morphgnt.txt:050428 V- 3AAI-S-- προώρισεν προώρισεν προώρισε(ν) προοράω

    66-Ro-morphgnt.txt:060829 V- 3AAI-S-- προώρισεν προώρισεν προώρισε(ν) προορίζω
    66-Ro-morphgnt.txt:060830 V- 3AAI-S-- προώρισεν, προώρισεν προώρισε(ν) προορίζω
    67-1Co-morphgnt.txt:070207 V- 3AAI-S-- προώρισεν προώρισεν προώρισε(ν) προορίζω

**Comment by jtauber** [comment]
If the lemma were προοράω, I'd expect προεῖδεν so is the Acts lemmatization just wrong?

**Comment by emg** [comment]
FWIW, Robinson's Westcott-Hort analyses the Acts instance as PROORI/ZW through Strong's number 4309.

**Comment by jtauber** [comment]
Yeah, I'm pretty sure προορίζω is correct.

**Comment by jtauber** [comment]
I mostly wanted a second pair of eyes in case I was missing something, so thanks @emg!

**Comment by emg** [comment]
Glad to be in His Majesty's Service with a man like you, @jtauber :-).
