### ISSUE TITLE
Names for each part of speech and parsing code column

### ISSUE THREAD

**Issue by scott-fleischman** [morphgnt/sblgnt#42]
It'd be useful to have a key in the readme for the part of speech codes and the possible values of each column in the parsing code.

**Comment by jtauber** [comment]
Parse codes are discussed in https://github.com/morphgnt/sblgnt/issues/1

Part of Speech are basically

A- adjective
C- conjunction
D- adverb
I- interjection
N- noun
P- preposition
RA definite article
RD demonstrative pronoun
RI interrogative/indefinite pronoun
RP personal pronoun
RR relative pronoun
V- verb
X- particle

but NOTE: these are the codes originally used by CCAT and I plan to soon stop using them.

**Comment by scott-fleischman** [comment]
It'd be helpful to include this kind of information in the readme, instead of in closed issues.

**Comment by jtauber** [comment]
@scott-fleischman done

**Comment by scott-fleischman** [comment]
Thanks!
