### ISSUE TITLE
Pronouns are person-less

### ISSUE THREAD

**Issue by enegue2** [morphgnt/sblgnt#54]
Hi,
I have noticed there is no "person" number for pronouns. Is this a "pending" task?

**Comment by jtauber** [comment]
Arguably pronouns don't inflect for person, each person is a different lexical item.

For example, it doesn't make sense to ask what the 3rd person dative singular of ἐγώ is or the 1st person accusative plural of σύ.

While it might be useful to provide lexical information on person, like the Robinson-based analyses do, I likely won't be doing this as part of MorphGNT itself, where, if anything, I want to reduce the lexical information and focus purely on indicating what is inflectional.

I'm even open to dropping number from the 1st and 2nd person personal pronouns as it is clearly lexical too.

**Comment by enegue2** [comment]
I understand what you are saying about "not really part of the morphology", but you have a field position for person, and the task of including "person" values for personal pronouns (RP), is quite simple. The work is pretty-much done, since there are only 8 unique lemmas for personal pronouns (person in parentheses): αλληλων, αυτος(3), εαυτου, εγω(1), εμαυτου(1), καγω(1), σεαυτου(2), συ(2). 

I have a BaseX script that creates a database from your text files, adding Strong's numbers and "person" values from RP lemmas.

I think I read somewhere in your comments that you weren't keen on being constrained by Strong's numbering, but it is useful for linking words to older reference data in the public domain.
